### ISSUE TITLE
ISO missing Partition Table

### ISSUE THREAD

**Issue by deca007** [covertsh/ubuntu-preseed-iso-generator#1]
@covertsh ISO boots up in vmware but throws this error while creating a bootable USB using Etcher
<img width="647" alt="etcher" src="https://user-images.githubusercontent.com/15268945/123150469-4280b680-d417-11eb-80c5-c0f337e08e1f.png">

**Comment by covertsh** [comment]
Hi, thank you for your issue report. I will look into this as soon as I get some time. I confirmed that the ISO produced by the tool does work for booting VMs, which was my own primary use case. I will try burning the ISO to USB and check whether that works too.

**Comment by jdorny** [comment]
You just need to run the isohybrid on the generated iso and it will be bootable. See this article: https://ferryhere.wordpress.com/2015/11/01/using-dd-to-create-a-bootable-usb-linux-system-from-iso-file/

**Comment by covertsh** [comment]
I think this will be resolved when I implement the fixes in https://github.com/covertsh/ubuntu-autoinstall-generator/issues/17#issuecomment-902525212.
