### ISSUE TITLE
Ubuntu 21.10 - 22.04 Removed isolinux

### ISSUE THREAD

**Issue by pdcq** [covertsh/ubuntu-preseed-iso-generator#5]
Hi,
Since Ubuntu 21.10 Desktop ISOLINUX has been removed from the orginal LiveCD ISO (the isolinux folder is missing from the build) and only EFI boot is supported (I suppose), so when using the script, it cannot build the ISO back again because the xorriso command is not correct anymore (no need for isohybrid anymore).
I tried to find the correct parameters, but run into a "bump" as the latest versions don't have /boor/grub/efi.img there's no .img file (of similar size) on the new iso.
I'm using this script (slightly modified) to insert several automatic installation options (mainly different locales). Works great with Ubuntu 20.04.
I have no clue where to look for the command(s) used to build the original ISO.

Hoping for a "quick fix" (at least the right xorriso command).

**Comment by hgneng** [comment]
I think this solution should help you:
https://askubuntu.com/questions/1289400/remaster-installation-image-for-ubuntu-20-10

It works for my xorriso command.

**Comment by pdcq** [comment]
Found a lot of useful information in that post.
But it still bumps for me:

mbr=...
efi=....
dest=.....

dd if="$orig" bs=1 count=446 of="$mbr"

skip=$(/sbin/fdisk -l "$orig" | fgrep '.iso2 ' | awk '{print $2}')
size=$(/sbin/fdisk -l "$orig" | fgrep '.iso2 ' | awk '{print $4}')
dd if="$orig" bs=512 skip="$skip" count="$size" of="$efi"

xorriso -as mkisofs -r -V "ubuntu-preseed" -J -joliet-long -l -iso-level 3 -partition_offset 16 --grub2-mbr "$mbr" --mbr-force-bootable -append_partition 2 0xEF "$efi" -appended_part_as_gpt -c boot.catalog -b boot/grub/i386-pc/eltorito.img -no-emul-boot -boot-load-size 4 -boot-info-table -eltorito-alt-boot -e '--interval:append_partition_2:all::' -no-emul-boot -o "$dest"

This fails:
xorriso 1.4.8 : RockRidge filesystem manipulator, libburnia project.

Drive current: -outdev 'stdio:test-22.04-desktop-amd64.iso'
Media current: stdio file, overwriteable
Media status : is blank
Media summary: 0 sessions, 0 data blocks, 0 data, 18.9g free
xorriso : WARNING : -volid text does not comply to ISO 9660 / ECMA 119 rules
xorriso : FAILURE : Cannot find in ISO image: -boot_image ... bin_path='/boot/grub/i386-pc/eltorito.img'
xorriso : aborting : -abort_on 'FAILURE' encountered 'FAILURE'

boot/grub/i386-pc/eltorito.img does exist in the temp. directory. 

I'm running the xorriso command manually from the temp folder (put a read -p in the original script to "hold").

**Comment by hgneng** [comment]
You miss a dot at the end of the command to specify current directory as the unpacked image directory.

**Comment by pdcq** [comment]
Indeed I had not noticed the dot was removed in all copy pasting.

This is the longest single line command I've ever seen.
After correcting another typo, this is the line I now use:
xorriso -as mkisofs -r -V "ubuntu-preseed" -J -joliet-long -l -iso-level 3 -partition_offset 16 --grub2-mbr "$mbr" --mbr-force-bootable -append_partition 2 0xEF "$efi" -appended_part_as_gpt -c boot.catalog -b boot/grub/i386-pc/eltorito.img -no-emul-boot -boot-load-size 4 -boot-info-table --grub2-boot-info -eltorito-alt-boot -e '--interval:appended_partition_2:all::' -no-emul-boot -o "${destination_iso}" .

If anyone wonders why I didn't split with "\", it is not working if you split lines (at least not for version 1.4.8

Running this xorriso command shows me some warnings:
libisofs: WARNING : Cannot add /dists/stable to Joliet tree. Symlinks can only be added to a Rock Ridge tree.
libisofs: WARNING : Cannot add /dists/unstable to Joliet tree. Symlinks can only be added to a Rock Ridge tree.
libisofs: WARNING : Cannot add /ubuntu to Joliet tree. Symlinks can only be added to a Rock Ridge tree.
libisofs: WARNING : Cannot add /dists/stable to Joliet tree. Symlinks can only be added to a Rock Ridge tree.
libisofs: WARNING : Cannot add /dists/unstable to Joliet tree. Symlinks can only be added to a Rock Ridge tree.
libisofs: WARNING : Cannot add /ubuntu to Joliet tree. Symlinks can only be added to a Rock Ridge tree.

But as it seems this doesn't affect the ubiquity installer.

Just for the record: the preseed files I had made for 20.04 don't exactly work for 22.04 (Ubiquity stops at the screen where you can select standard or minimal installation, and 3rd party drivers selection). 

I hope the maintaner of this project has some time to update his work.
